app = "weather-data-api"
primary_region = "fra"

[build]

[env]
  PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

  [[http_service.concurrency]]
    type = "connections"
    hard_limit = 25
    soft_limit = 20 