app = "weather-data-api"
primary_region = "fra"

[build]

[env]
  PORT = "443"

[[services]]
  protocol = "tcp"
  internal_port = 443
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

  [[services.ports]]
    port = 443
    handlers = ["tls"]

  [[services.ports]]
    port = 80
    handlers = ["http"]

[http_service]
  internal_port = 443
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1 